name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🔔

        uses: actions/checkout@v3

      - name: Inject Supabase Credentials 🔑
        run: |
          sed -i 's|%%SUPABASE_URL%%|${{ secrets.SUPABASE_URL }}|g' index.html
          sed -i 's|%%SUPABASE_ANON_KEY%%|${{ secrets.SUPABASE_ANON_KEY }}|g' index.html

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

